- hosts: leaf
  connection: httpapi
  gather_facts: false
  collections:
    - dellemc.enterprise_sonic

  tasks:
   - name: "bgp af overlay configuration"
     sonic_bgp_af:
      config:
       - bgp_as: "{{bgp_asn}}"
         address_family:
          afis:
          - afi: l2vpn
            safi: evpn
            advertise_all_vni: True

   - name: "bgp neighbors af overlay configuration"
     sonic_bgp_neighbors_af:
      config:
       - bgp_as: "{{bgp_asn}}"
         neighbors:
          - neighbor: '{{spine1_int1}}'
            address_family:
             - afi: l2vpn
               safi: evpn
               activate: true
          - neighbor: '{{spine2_int1}}'
            address_family:
             - afi: l2vpn
               safi: evpn
               activate: true
